/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 cartridge.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cartridge.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cartridge004.geometry} material={materials.cartridgeImported} />
    </group>
  )
}

useGLTF.preload('/cartridge.glb')
